### ISSUE TITLE
CPU Speed Not Showing

### ISSUE THREAD

**Issue by Darkchilde** [Mayochun/Rainmeter-Sys-Monitor#1]
CPU skin is not showing the CPU speed. Checked and made sure that my CPU is supported by coretemp, and it is. Not sure what could be the issue.

**Comment by Tsubakimochi** [comment]
Is it only CPU Speed that is not displayed?
Are CPU Temp and Power displayed?

**Comment by Darkchilde** [comment]
Yes, CPU Temp and Power display correctly. It is only CPU speed.

**Comment by Tsubakimochi** [comment]
I don't know the cause either, but try running the [CoreTemp plugin-Example in the Rainmeter documentation](https://docs.rainmeter.net/manual/plugins/coretemp/). If CPU Speed (Frequency) is still not displayed, there may be a problem with the plugin.
If the CPU Speed is displayed in the Example, we will consider the countermeasure here.

**Comment by Darkchilde** [comment]
I have tried moving the CPU.ini to another folder, creating a new CPU.ini file and pasting the example information into the file. This does allow for the CPU speed to be shown. So I'm looking through the CPU.ini file you created to see if there is anything I can determine might be causing a conflict, but have had no luck so far.

**Comment by Darkchilde** [comment]
Alright, just to clear things up, I started with your download from the releases section. That is the version of CPU.ini that isn't working properly. I just tried replacing it with the latest version of CPU.ini downloaded using the download zip option under code. That version is working correctly for me. So consider this issue closed. Thank you for your attention to this matter.

**Comment by Tsubakimochi** [comment]
Glad we were able to resolve this! Let's say you have solved the issue by releasing the latest code.
Thank you!
